name: Publish maneric-charts to npm

on:
  push:
    tags:
      - 'v*.*.*' # publish only when you push a version tag like v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build library
      - name: Build Angular library
        run: npm run build maneric-charts

      # 5. Publish to npm
      - name: Publish to npm
        run: npm publish --access public
        working-directory: dist/maneric-charts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
